name: CI

on:
  push:
    branches:
      - '**' 

jobs:
  build:
    name: Building and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout engine repo
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        #ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        repository: SmartUserName/PragmaticP-TZ@main
      
    - name: List files
      run: |
        ls -la

    - name: Update tag
      run: |
        # Determine the tag to use based on the branch name or tag event
        if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
          TAG="latest"
        else
          TAG="branch"
        fi
        echo $TAG
        
      
        # cat ./tz/terraform/providers.tf | grep "region"
        # tag=$(cat ./tz/terraform/providers.tf | grep "region" | awk '{print $3}')
        # echo $tag
        # sed -i "s/$tag/eu-west-2/" ./tz/terraform/providers.tf
        # cat ./tz/terraform/providers.tf
        # git config --global user.email "test@example.com"
        # git config --global user.name "Actions"
        # git status
        # git add -A
        # git commit -m "test actions"
        # echo 'commit done'
        # git push origin main
