name: CI

on:
    push:
      branches: [ master ]

jobs:
  build:
    name: Building and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout engine repo
      uses: actions/checkout@v3
      with:
        #ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        repository: SmartUserName/terraform-up-and-running-code
      
    - name: List files
      run: |
        ls -la

    - name: Update tag
      run: |
        cat ./code/bash/01-why-terraform/setup-webserver.sh | grep "service apache2"
        tag=$(cat ./code/bash/01-why-terraform/setup-webserver.sh | grep "service apache2" | awk '{print $2}')
        echo $tag
        sed -i "s/$tag/stop/" ./code/bash/01-why-terraform/setup-webserver.sh 
        cat ./code/bash/01-why-terraform/setup-webserver.sh

    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        commit_message: Version updated
