name: CI

on:
    push:
      branches: [ main ]

jobs:
  build:
    name: Building and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout engine repo
      uses: actions/checkout@v3
      with:
        #ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        repository: SmartUserName/terraform-up-and-running-code
      
    - name: List files
      run: |
        ls -la
